[package]
name = "taiko-reth"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[[bin]]
name = "taiko-reth"
path = "src/bin/main.rs"

[lib]
name = "taiko_reth"
path = "src/lib.rs"

[dependencies]
# reth
reth = { git = "https://github.com/paradigmxyz/reth", package = "reth", tag = "v1.5.1" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-payload-validator = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-ethereum-forks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.5.1" }

# alloy
alloy-eips = { version = "1.0.18", default-features = false }
alloy-genesis = { version = "1.0.18", default-features = false }
alloy-consensus = { version = "1.0.18", default-features = false, features = [
  "arbitrary",
] }
alloy-evm = { version = "0.14", default-features = false }
alloy-rpc-types-eth = { version = "1.0.18", default-features = false }
alloy-primitives = { version = "1.0.18", default-features = false }
alloy-serde = { version = "1.0.18", default-features = false }
alloy-rpc-types-txpool = { version = "1.0.18", default-features = false }
alloy-rpc-types-trace = { version = "1.0.18", default-features = false }
alloy-json-rpc = { version = "1.0.18", default-features = false }
alloy-network = { version = "1.0.18", default-features = false }
alloy-signer = { version = "1.0.18", default-features = false }
alloy-rpc-types-engine = { version = "1.0.18", default-features = false }
alloy-tx-macros = { version = "1.0.18", default-features = false }
alloy-rpc-client = { version = "1.0.18", default-features = false }
alloy-chains = { version = "0.2.5", default-features = false }
alloy-hardforks = "0.2.7"
alloy-rlp = { version = "0.3.10", default-features = false, features = [
  "core-net",
] }
op-alloy-flz = { version = "0.13.1", default-features = false }

# revm
revm-database-interface = { version = "7.0.1", default-features = false }

# rpc
jsonrpsee = "0.25.1"
jsonrpsee-core = "0.25.1"
jsonrpsee-server = "0.25.1"
jsonrpsee-http-client = "0.25.1"
jsonrpsee-types = "0.25.1"

# mis
cc = "=1.2.15"
eyre = "0.6"
arbitrary = "1.3"
clap = "4"
async-trait = "0.1.68"
parity-scale-codec = "3.2.1"
parking_lot = "0.12"
tokio-retry = "0.3"
tracing = { version = "0.1.0", default-features = false }
derive_more = { version = "2", default-features = false, features = ["full"] }
sha2 = { version = "0.10", default-features = false }
thiserror = { version = "2.0.0", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3", default-features = false, features = [
  "macros",
  "base64",
] }

[features]
default = ["serde"]
serde = ["serde/derive"]
client = []
arbitrary = ["alloy-consensus/arbitrary"]
