name: Claude Code

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  claude-code:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && 
       github.event.pull_request.draft == false && 
       (contains(github.event.pull_request.body || '', '@claude') || 
        contains(github.event.pull_request.title || '', '@claude'))) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body || '', '@claude'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Delete previous Claude comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            for (const comment of comments.data) {
              if (comment.user.login === 'github-actions[bot]' && 
                  comment.body.includes('Claude Code Review')) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                });
              }
            }
        
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          custom_instructions: |
            You are a helpful code reviewer. Focus on:
            - Code quality and best practices in Rust
            - Potential bugs or issues
            - Performance improvements
            - Security concerns
            - Code style and formatting
            - Code documentation
            - Provide a summary of the changes in the PR