name: Claude Code Debug

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Comment Event
        run: |
          echo "=== EVENT DEBUG ==="
          echo "Event Name: ${{ github.event_name }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Is PR: ${{ github.event.issue.pull_request != null }}"
          echo "PR URL: ${{ github.event.issue.pull_request.url || 'Not a PR' }}"
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Contains @claude: ${{ contains(github.event.comment.body, '@claude') }}"
          echo "=================="